### ISSUE TITLE
Step fails with error code 126 

### ISSUE THREAD

**Issue by markopoinz** [guness/bitrise-step-firebase-app-distribution#59]
Hi, we were using this step for a long time and it is very useful.

We started having problems with this once we moved to the node v18 because we updated react native to v73 which requires node >= 18. 

Also I can confirm that node v18.16.0 is installed globally in this workflow. See screenshot bellow. I added this step just to be sure it's installed correctly just before we run firebase-app-distribution step.

![Screenshot 2024-01-25 at 13 55 24](https://github.com/guness/bitrise-step-firebase-app-distribution/assets/157501963/2cffa28e-5908-4e09-b666-ed4898caea42)

Workflow is designed to test, build and release the app to app distribution so that our internal testers can check the new release.

After .apk is created we are running firebase-app-distribution step which fails with the error code 126.

**Peice of bitrise.yml:**
```
deploy-firebase:
    steps:
    - firebase-app-distribution@0:
        inputs:
        - app: $FIREBASE_APP_ID
        - upgrade_firebase_tools: "true"
        - groups: $FIREBASE_TESTER_GROUPS
        - service_credentials_file: $FIREBASE_SERVICE_ACCOUNT
        - release_notes_file: $RELEASE_NOTES_FILE
```

**Screenshot of the error log:**
![Screenshot 2024-01-25 at 13 42 14](https://github.com/guness/bitrise-step-firebase-app-distribution/assets/157501963/ffe1f3e8-260c-456b-9767-09606203cc26)

Do you know how can we fix this issue?
